### ISSUE TITLE
Undefined StreamController, undefined PersonMapper

### ISSUE THREAD

**Issue by grappetite-ali** [vitusortner/floor#110]
After running command `flutter packages pub run build_runner build`, i am getting syntax error in database.g.dart file which is _undefined StreamController_ and undefined _PersonMapper_.

**pubspec.yaml**
```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  floor: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.2.0
  build_runner: ^1.2.8

```

**database.dart**
```
import 'package:floor/floor.dart';
import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart' as sqflite;
import './person.dart';
import './person-dao.dart';

part 'database.g.dart'; // the generated code will be there

@Database(version: 1, entities: [Person])
abstract class AppDatabase extends FloorDatabase {
  static Future<AppDatabase> openDatabase() async => _$open();

  PersonDao get personDao;
}
```

**person.dart**
```
import 'package:floor/floor.dart';

@entity
class Person {
  @primaryKey
  final int id;

  final String name;

  Person(this.id, this.name);
}
```

**person-dao.dart**
```
import 'package:floor/floor.dart';
import './person.dart';

@dao
abstract class PersonDao {
  @Query('SELECT * FROM Person')
  Future<List<Person>> findAllPersons();

  @Query('SELECT * FROM Person WHERE id = :id')
  Future<Person> findPersonById(int id);

  @insert
  Future<void> insertPerson(Person person);
}
```
