### ISSUE TITLE
Can't primaryKey be String type?

### ISSUE THREAD

**Issue by Henvealf** [vitusortner/floor#313]
When I create a entity like this: 
```
class User {
  @PrimaryKey()
  final String id;
}
```

After `flutter packages pub run build_runner build`, the dao mapper of generated in `*.g.dart` file is :
```
id: row['id'] as double,
```

I need to change it manually every build as:

```
id: row['id'] as String,
```
Otherwise it won't work when operate db :

```
type 'String' is not a subtype of type 'double' in type cast
```

Is this a bug？

Version：

```
dependencies:
  floor: ^0.12.0

dev_dependencies:
  floor_generator: ^0.12.0
  build_runner: ^1.7.3
```
