### ISSUE TITLE
Errors under testing using SQFlite

### ISSUE THREAD

**Issue by TheKewlStore** [vitusortner/floor#363]
I am having troubles using the database in a test environment via android studio. It seems the generated code does not have what it expects from sqflite in this environment, as the generated code complains that it can't find `sqflite.getDatabasesPath()` and `sqflite.openDatabase()` functions. 

I tried to copy your test examples as best as I could, like so:

I created a separate FloorDatabase subclass called TestDatabase. In there, I use this import for sqflite:

`import 'package:sqflite/sqlite_api.dart' as sqflite; // Using the normal import of sqflite gives me a different error saying the plugin does not exist.`

In my test case, I've done the following to try and initialize everything:

```
TestWidgetsFlutterBinding.ensureInitialized();

  group("Synchronization Tests", () {
    TestDatabase database;

    setUp(() async {
      database = await $FloorTestDatabase.inMemoryDatabaseBuilder().build();
    });
```

Is this a sqflite version error or something else entirely?

**Comment by mqus** [comment]
> Is this a sqflite version error or something else entirely?

This reads exactly like an sqlflite version error like in #345, which was adressed in #355, but not yet released.

Seeing that those issues keep appearing and the currently open PRs are not ready soon, I would propose a release of 0.13.1, which contains your PR and the dependency update. What do you think, @vitusortner?

**Comment by TheKewlStore** [comment]
In the meantime, can I force floor to use a later version of sqflite manually? Like if I include it in my project's pubspec, will that override it? (Still a little new to flutter in general)

**Comment by vitusortner** [comment]
You should have two options: Run `flutter pub upgrade` or use [pub's dependency override capabilities](´https://dart.dev/tools/pub/dependencies#dependency-overrides) to define a specific sqflite version (which should be 1.3.0 or newer).

@mqus I'll create a release right away 👍

**Comment by TheKewlStore** [comment]
For mine to work properly, I actually needed to make two changes to my pubspec:

```
dependencies:
  sqflite_common_ffi: ^1.0.0+2

dependency_overrides:
  sqflite: ^1.3.0+2
```

Not sure if both of these are necessary or if I just needed to specify sqflite 1.3.0+2 instead of only 1.3.0.

**Comment by TheKewlStore** [comment]
Just tried updating to the latest version (0.13.0) and the generation fails with an error along the lines of "FloorGenerator failed, null value encountered"

**Comment by mqus** [comment]
@TheKewlStore could you share the exact error? That sounds like it is another issue. 

A new version was not released yet, 0.13.0 is from May.

**Comment by TheKewlStore** [comment]
Oh, so i've been using an older version this whole time haha.

Just so there isn't any confusion, here is what my pubspec looks like with my current working configuration (pared down to what i believe is relevant):

```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  floor: ^0.12.0
  sqflite_common_ffi: ^1.0.0+2
  sqflite: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  floor_generator: ^0.12.0
  build_runner: ^1.7.3
```

And here is how i modified it to use floor 0.13.0.

```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  floor: ^0.13.0
  sqflite_common_ffi: ^1.0.0
  sqflite: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  floor_generator: ^0.13.0
  build_runner: ^1.7.3
```

I removed the +2's as you mentioned, that removed the !sqflite 1.3.1 error but didn't fix the generation. On 0.13.0 it still doesn't work in either case. Here is the exact errors that i get when running build_runner (which are not very useful, is there like a verbose flag i can pass or anything)?

[SEVERE] floor_generator:floor_generator on test/test_database.dart (cached):
Error running FloorGenerator
Bad state: No element
[SEVERE] floor_generator:floor_generator on lib/database.dart (cached):
Error running FloorGenerator
Bad state: No element
[SEVERE] Failed after 167ms

I've tried to do a flutter clean as well to no avail, thinking maybe some stale version information was left behind.
