### ISSUE TITLE
Add option for renaming table and column names

### ISSUE THREAD

**Issue by marcosmko** [vitusortner/floor#386]
I would like to suggest a new feature inspired by json_serializable.

The naming convention for Dart is lowerCamelCase.
As SQL is a commonly used database, everyone has its preferences for naming tables and columns.

As such, we could have an option as [json_serializable](https://pub.dev/documentation/json_annotation/latest/json_annotation/FieldRename-class.html) offers in build.yaml:

```yaml
targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: none/pascal/kebab/snake [as lowerCamelCase is default for dart, `none` would also be lowerCamelCase)
```

In a example, the following class
```dart
@Entity()
class MyClass {
  MyClass({this.aLongVariableName});
  String aLongVariableName;
}
```

the variable ```aLongVariableName``` would be mapped to ```a_long_variable_name``` column name, when using the snake case option.
