### ISSUE TITLE
floor_generator build dependency

### ISSUE THREAD

**Issue by amkuchta** [vitusortner/floor#518]
Currently, `floor_generator` depends on an older version of `build`, `^1.6.3`.  This causes incompatibilities with other packages that utilizes the latest versions, `>=2.0.0 <2.1.01`

**Comment by proninyaroslav** [comment]
As a workaround:
```yaml
dependency_overrides:
  build: ^2.0.0
  source_gen: ^1.0.0
```
