### ISSUE TITLE
Pub Get fails because of floor_generator's build_runner 1.6.3 dependency

### ISSUE THREAD

**Issue by MrCsabaToth** [vitusortner/floor#523]
```Because floor_generator >=1.0.0-nullsafety.1 depends on build ^1.6.3 and build_runner >=1.12.0 depends on build >=2.0.0 <2.1.0, floor_generator >=1.0.0-nullsafety.1 is incompatible with build_runner >=1.12.0.
So, because track_my_indoor_exercise depends on both build_runner ^1.12.2 and floor_generator ^1.0.0, version solving failed.
pub get failed (1; So, because track_my_indoor_exercise depends on both build_runner ^1.12.2 and floor_generator ^1.0.0, version solving failed.)
```

I don't know where's the 1.6.3 coming from. As far as I see in the source repo the `floor_generator` depends on `build: ^2.0.0`.

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

• No issues found!
```

My pubspec.yaml:
```
publish_to: "none"

version: 1.1.21+30

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  assorted_layout_widgets: ^4.0.1
  charts_flutter: ^0.10.0
  convert: ^3.0.0
  datetime_picker_formfield: ^2.0.0
  device_info: ^2.0.0
  expandable: ^5.0.1
  fab_circular_menu: ^1.0.2
  file_picker: ^3.0.0
  floor: ^1.0.0
  flutter_blue:
    git:
      url: https://github.com/MrCsabaToth/flutter_blue.git
      ref: patch-1
  flutter_brand_icons: ^1.1.0
  get: ^4.0.0-nullsafety.2
  http: ^0.13.1
  http_parser: ^4.0.0
  internet_connection_checker: ^0.0.1
  intl: ^0.17.0
  listview_utils:
    git:
      url: https://github.com/WaleedAlrashed/flutter-listutils.git
  loading_overlay: ^0.3.0
  meta: ^1.2.4
  preferences: any
  progress_indicators: ^0.1.5
  rxdart: ^0.26.0
  share_files_and_screenshot_widgets: ^1.0.3
  shared_preferences: ^2.0.5
  spinner_input: ^0.1.2
  sqflite: ^2.0.0+3
  tuple: ^2.0.0
  uni_links2: ^0.6.0+2
  url_launcher: ^6.0.3
  wakelock: ^0.5.0+2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.12.2
  floor_generator: ^1.0.0
  integration_test: ^1.0.2+2
  mockito: ^5.0.3
  mock_data: ^1.2.8
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
```

**Comment by MrCsabaToth** [comment]
I wiped `~/.pub-cache`. After that I can see in the `~/.pub-cache/hosted/pub.dartlang.org/.cache/floor_generator-versions.json` that it is indeed references 1.6.3 build.

**Comment by MrCsabaToth** [comment]
OK, I see that https://github.com/vitusortner/floor/commit/2a762675b0f543af296ddee33b7ef66e1ae939ff is only 4 days old and not released. How could I reference the current git repo version in my pubspec? If I try:

```
  floor:
    git:
      url: https://github.com/vitusortner/floor.git
      path: floor
```
That works. However
```
  floor_generator:
    git:
      url: https://github.com/vitusortner/floor.git
      path: floor_generator
```
Does not, because `Invalid description in the "floor_generator" pubspec on the "floor_annotation" dependency: "../floor_annotation/" is a relative path, but this isn't a local pubspec.`
``
