### ISSUE TITLE
floor_generator >=1.2.0 depends on meta ^1.7.0  flutter sdk depends on meta 1.3.0

### ISSUE THREAD

**Issue by Sispheor** [vitusortner/floor#612]
Hi,

I'm a bit new in dart/flutter world. So sorry if it's a nooby question.

I have this error when trying to install Floor:
```bash
flutter pub get         
Because floor_generator >=1.2.0 depends on meta ^1.7.0 and every version of flutter_test from sdk depends on meta 1.3.0, floor_generator >=1.2.0 is incompatible with flutter_test from sdk.
So, because day_off_tracker depends on both flutter_test any from sdk and floor_generator ^1.2.0, version solving failed.
Running "flutter pub get" in day_off_tracker...                         
pub get failed (1; So, because day_off_tracker depends on both flutter_test any from sdk and floor_generator ^1.2.0, version solving failed.)
```

pubspec:
```yaml
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.2.0
  cupertino_icons: ^1.0.2
  percent_indicator: 3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.2.0
  build_runner: ^2.1.2
```

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.1)
[✓] Connected device (2 available)

• No issues found!
```

As a workaround I can remove the fixed version of `floor_generator` and `floor`. But then the installed version is 1.1.0.

Thanks for your help.
