### ISSUE TITLE
upgrade analyzer 

### ISSUE THREAD

**Issue by BelongsH** [vitusortner/floor#641]
Thanks you libary ,  I found a problem, however, I can't fix it. hope you can help me。

I clone develop branch code , then run 

```
flutter packages pub run build_runner build
```

show  error such as 

```
Value of onConflict must be one of OnConflictStrategy.replace,OnConflictStrategy.rollback,OnConflictStrategy.abort,OnConflictStrategy.fail,OnConflictStrategy.ignore
package:example/task_dao.dart:16:16
   ╷
16 │   Future<void> insertTask(Task task);
   │                ^^^^^^^^^^
   ╵
[INFO] Running build completed, took 4.9s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 15ms

```

I guess `insert` anotation not recognized ，so an error like this occurs。

My computer environment is 

```
flutter 2.11.0-0.0.pre.478 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0b27dd6b47 (2 hours ago) • 2022-02-08 08:15:08 -0500
Engine • revision 7bf74069a5
Tools • Dart 2.17.0 (build 2.17.0-87.0.dev) • DevTools 2.10.0
```

**Comment by xiazunyang** [comment]
I had the same problem and here is my configuration:
```
  floor_generator:
    git:
      url: git://github.com/Cilestal/floor.git
      ref: develop
      path: floor_generator/
``` 
I can only use this because I also use Retrofit to generate code to access the network, and RetroFIT_generator relies on Analyzer ^3.0.0
```
because retrofit_generator 4.0.1 depends on analyzer ^3.0.0 and no versions of retrofit_generator match >4.0.1 <5.0.0, floor_generator is incompatible with retrofit_generator ^4.0.1.
```

**Comment by BelongsH** [comment]
@xiazunyang 

I try to use git dependencies
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator:
    git:
      url: git://github.com/Cilestal/floor.git
      ref: develop
      path: floor_generator/

```
and 
```
dependencies:
  flutter:
    sdk: flutter
  floor:
    git:
      url: git://github.com/Cilestal/floor.git
      ref: develop
      path: floor/
```
then clean git cache and run flutter clean 

get the same result
